import '../../ui/components/common/masonry_grid/masonry_grid';
import '../../ui/components/technologies/technologies_descriptions_form/technologies_descriptions_form';
import '../../ui/components/technologies/technologies_descriptions_panel/technologies_descriptions_panel';
import '../../ui/components/technologies/technologies_descriptions_tabs/technologies_descriptions_tabs';
import '../../ui/components/technologies/technologies_images_input/technologies_images_input';
import '../../ui/components/technologies/technologies_images_item/technologies_images_item';
import '../../ui/components/technologies/technologies_information_card/technologies_information_card';
// import '../../ui/components/technologies/technologies_information_form/technologies_information_form';
import '../../ui/components/technologies/technologies_information_table/technologies_information_table';
import '../../ui/components/technologies/technologies_status_form/technologies_status_form';
