this["TDB"] = this["TDB"] || {};
this["TDB"]["templates"] = this["TDB"]["templates"] || {};
this["TDB"]["templates"]["attachmentCard"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "  <div class=\"ibox card-box cards-item\">\n    <div class=\"ibox-content no-padding card-label\">\n      <div class=\"card-tools\">\n        <div class=\"btn-group\">\n          <button data-toggle=\"dropdown\" class=\"btn btn-xs btn-white dropdown-toggle\" aria-expanded=\"false\"><i class=\"fa fa-paperclip\"></i> <span class=\"caret\"></span></button>\n          <ul class=\"dropdown-menu\">\n            <li><a href=\"#\">Add to Project</a></li>\n            <li><a href=\"#\">Add to Technology</a></li>\n            <li><a href=\"#\">Add an Organization</a></li>\n            <li class=\"divider\"></li>\n            <li><a href=\"#\">Edit</a></li>\n            <li><a href=\"#\">Delete</a></li>\n          </ul>\n        </div>\n      </div>\n      <a href=\"attachmentEntry.php\"><img src=\""
    + alias4(((helper = (helper = helpers.src || (depth0 != null ? depth0.src : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"src","hash":{},"data":data}) : helper)))
    + "\" class=\"img-responsive\" /></a>\n      <div class=\"card-description\">\n          <h5 class=\"card-name\"><a href=\"attachmentEntry.php\">"
    + alias4(((helper = (helper = helpers.name || (depth0 != null ? depth0.name : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data}) : helper)))
    + "</a></h5>\n        <p>"
    + alias4(((helper = (helper = helpers.description || (depth0 != null ? depth0.description : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"description","hash":{},"data":data}) : helper)))
    + "</p>\n        <div class=\"btn-group\">\n          <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"View Entry\"><a href=\"attachmentEntry.php\"><i class=\"fa fa-eye\"></i></a></button>\n          <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"Status is Published\">"
    + alias4(((helper = (helper = helpers.type || (depth0 != null ? depth0.type : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"type","hash":{},"data":data}) : helper)))
    + "</button>\n          <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"11 technologies\"><i class=\"fa fa-gear\"></i> 11</button>\n          <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"04 organizations\"><i class=\"fa fa-building\"></i> 4</button>\n          <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"02 projects\"><i class=\"fa fa-folder-o\"></i> 2</button>\n        </div>\n      </div>\n    </div>\n  </div>";
},"useData":true});;