this["TDB"] = this["TDB"] || {};
this["TDB"]["templates"] = this["TDB"]["templates"] || {};
this["TDB"]["templates"]["organizationCard"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<!-- Começo Organização -->\n<div class=\"cards-item\">\n    <div class=\"ibox technology-box\">\n        <div class=\"ibox-content no-padding techLabel\">\n            <div class=\"technologyTools\">\n                <div class=\"btn-group\">\n                    <button data-toggle=\"dropdown\"  class=\"btn btn-xs btn-white dropdown-toggle\" aria-expanded=\"false\"><i class=\"fa fa-building\"></i> <span class=\"caret\"></span></button>\n                    <ul class=\"dropdown-menu\">\n                        <li>\n                            <a href=\"#\">View Collections</a>\n                        </li>\n                        <li>\n                            <a href=\"#\">Add technologies to Stash</a>\n                        </li>\n                        <li>\n                            <a href=\"#\">Change status</a>\n                        </li>\n                        <li>\n                            <a href=\"#\">Edit status</a>\n                        </li>\n                        <li class=\"divider\"></li>\n                        <li>\n                            <a href=\"#\">Edit technology</a>\n                        </li>\n                        <li>\n                            <a href=\"#\">Delete technology</a>\n                        </li>\n                    </ul>\n                </div>\n                <div class=\"btn-group\">\n                </div>\n            </div>\n            <a href=\"#/organizations/entry\"><img src=\""
    + alias4(((helper = (helper = helpers.src || (depth0 != null ? depth0.src : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"src","hash":{},"data":data}) : helper)))
    + "\" class=\"img-responsive\" /></a>\n            <div class=\"technology-desc\">\n                <div>\n                    <h5 class=\"technology-name\"><a href=\"organizationEntry.php\">"
    + alias4(((helper = (helper = helpers.name || (depth0 != null ? depth0.name : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data}) : helper)))
    + "</a></h5>\n                </div>\n                <p>"
    + alias4(((helper = (helper = helpers.description || (depth0 != null ? depth0.description : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"description","hash":{},"data":data}) : helper)))
    + "</p>\n                <div class=\"btn-group\">\n                    <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"View Entry\"><a href=\"organizationEntry.php\"><i class=\"fa fa-eye\"></i></a></button>\n                    <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"Private\">"
    + alias4(((helper = (helper = helpers.type || (depth0 != null ? depth0.type : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"type","hash":{},"data":data}) : helper)))
    + "</button>\n                    <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"12 technologies\"><i class=\"fa fa-gear\"></i> 12</button>\n                    <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"03 projects\"><i class=\"fa fa-folder-o\"></i> 03</button>\n                    <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"11 attachments\"><i class=\"fa fa-paperclip\"></i> 11</button>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>\n<!-- Fim organização-->";
},"useData":true});;