this["TDB"] = this["TDB"] || {};
this["TDB"]["templates"] = this["TDB"]["templates"] || {};
this["TDB"]["templates"]["projectCard"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<div class=\"ibox card-box cards-item\">\n  <div class=\"ibox-content no-padding card-label\">\n    <div class=\"card-tools\">\n      <div class=\"btn-group\">\n        <button data-toggle=\"dropdown\" class=\"btn btn-xs btn-white dropdown-toggle\" aria-expanded=\"false\"><i class=\"fa fa-folder\"></i> <span class=\"caret\"></span></button>\n        <ul class=\"dropdown-menu\">\n          <li>\n            <a href=\"#\">View Collections</a>\n          </li>\n          <li>\n            <a href=\"#\">Add technologies to Stash</a>\n          </li>\n          <li>\n            <a href=\"#\">Change status</a>\n          </li>\n          <li>\n            <a href=\"#\">Edit status</a>\n          </li>\n          <li class=\"divider\"></li>\n          <li>\n            <a href=\"#\">Edit technology</a>\n          </li>\n          <li>\n            <a href=\"#\">Delete technology</a>\n          </li>\n        </ul>\n      </div>\n    </div>\n    <a href=\"#/projects/entry\"><img src=\""
    + alias4(((helper = (helper = helpers.src || (depth0 != null ? depth0.src : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"src","hash":{},"data":data}) : helper)))
    + "\" class=\"img-responsive\" /></a>\n    <div class=\"card-description\">\n      <h5 href=\"#\" class=\"card-name\"><a href=\"#/projects/entry\"><span class=\"card-id\">"
    + alias4(((helper = (helper = helpers.evID || (depth0 != null ? depth0.evID : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"evID","hash":{},"data":data}) : helper)))
    + "</span> "
    + alias4(((helper = (helper = helpers.name || (depth0 != null ? depth0.name : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data}) : helper)))
    + "</a></h5>\n      <p>"
    + alias4(((helper = (helper = helpers.description || (depth0 != null ? depth0.description : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"description","hash":{},"data":data}) : helper)))
    + "</p>\n      <div class=\"btn-group\">\n        <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"View Entry\"><a href=\"projectEntry.php\"><i class=\"fa fa-eye\"></i></a></button>\n        <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"Open project\">"
    + alias4(((helper = (helper = helpers.status || (depth0 != null ? depth0.status : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"status","hash":{},"data":data}) : helper)))
    + "</button>\n        <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"12 technologies\"><i class=\"fa fa-gear\"></i> 12</button>\n        <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"11 collections\"><i class=\"fa fa-archive\"></i> 11</button>\n        <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"11 attachments\"><i class=\"fa fa-paperclip\"></i> 11</button>\n      </div>\n    </div>\n  </div>\n</div>\n";
},"useData":true});;