this["TDB"] = this["TDB"] || {};
this["TDB"]["templates"] = this["TDB"]["templates"] || {};
this["TDB"]["templates"]["technologyCard"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<div class=\"cards-item\">\n  <div class=\"ibox technology-box\">\n    <div class=\"ibox-content no-padding techLabel panel-primary\">\n      <div class=\"technologyTools\">\n        <div class=\"btn-group\">\n          <button data-toggle=\"dropdown\" class=\"btn btn-xs btn-white dropdown-toggle\" aria-expanded=\"false\"><i class=\"fa fa-gear\"></i> <span class=\"caret\"></span></button>\n          <ul class=\"dropdown-menu\">\n            <li>\n              <a href=\"#\">Add to Project</a>\n            </li>\n            <li>\n              <a href=\"#\">Add to Collection</a>\n            </li>\n            <li>\n              <a href=\"#\">Add an Attachment</a>\n            </li>\n            <li>\n              <a href=\"#\">Change status</a>\n            </li>\n            <li class=\"divider\"></li>\n            <li>\n              <a href=\"#\">Add a comment</a>\n            </li>\n            <li>\n              <a href=\"#\">Edit status</a>\n            </li>\n            <li class=\"divider\"></li>\n            <li>\n              <a href=\"technologyEdit.php\">Edit technology</a>\n            </li>\n            <li>\n              <a href=\"#\">Delete technology</a>\n            </li>\n          </ul>\n        </div>\n      </div>\n      <a href=\"#/technologies/entry\"><img src=\""
    + alias4(((helper = (helper = helpers.src || (depth0 != null ? depth0.src : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"src","hash":{},"data":data}) : helper)))
    + "\" class=\"img-responsive\" /></a>\n      <div class=\"technology-desc\">\n        <div>\n          <h5 class=\"technology-name\"><a href=\"#/technologies/entry\"><span class=\"card-id\">T0021</span> "
    + alias4(((helper = (helper = helpers.name || (depth0 != null ? depth0.name : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data}) : helper)))
    + "\n</a></h5>\n          <div class=\"btn-group btn-xs btn-addons\">\n            <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"Readiness: 4\"><i class=\"fa fa-bullseye\"></i> 4</button>\n            <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"Average Industry Impact: 4\"><i class=\"fa fa-rocket\"></i> 4</button>\n          </div>\n        </div>\n        <p>"
    + alias4(((helper = (helper = helpers.description || (depth0 != null ? depth0.description : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"description","hash":{},"data":data}) : helper)))
    + "</p>\n        <div class=\"btn-group\">\n          <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"View Entry\"><a href=\"technologyEntry.php\"><i class=\"fa fa-eye\"></i></a></button>\n          <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"Status is <?php echo $technology[$id][4]; ?>\">Published</button>\n          <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"11 attachments\"><i class=\"fa fa-paperclip\"></i> 11</button>\n          <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"02 projects\"><i class=\"fa fa-folder-o\"></i> 2</button>\n          <button class=\"btn btn-xs btn-outline btn-primary\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"04 organizations\"><i class=\"fa fa-building\"></i> 4</button>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n";
},"useData":true});;